version: '3'
services:
  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
  web:
    image: "chatapp"
    ports:
      - "8000:8000"  # external:internal
    command: sh /code/runserver.sh
    volumes:
      - .:/code
    links:
      - redis
      - postgres
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  #node:
  #  image: "node"
  #  command: sh /code/run_node_server.sh
  #  volumes:
  #    - .:/code
  #  links:
  #    - web
  #  ports:
  #    - "3000:3000"
  nginx:
    image: "nginx:alpine"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
    links:
      - web
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
